### ISSUE TITLE
识别不了不带bom的UTF-8

### ISSUE THREAD

**Issue by yansheng836** [briarbear/gbk_to_utf8#1]
UTF-8带BOM和UTF-8不带BOM是不一样的，你这个程序检测不出来不带bom的UTF-8。

亲测：
1. 如果你确认你需要转的文件全是gbk，该程序可以实现批量转UTF-8（不带bom的）；
2. 但是如果你继续用该程序扫描该文件夹，那么恭喜你:innocent:全乱了（如需尝试，请预先备份重要文件）。

**Comment by briarbear** [comment]
哈哈，这个当时写得是转GBK到UTF-8（without bom），其他的没考虑那么多，有兴趣你可以fork改进下

**Comment by briarbear** [comment]
这个最开始的应用场景是：文档中有都是GBK编码，且出现乱码，所以可以使用该工具尝试转码。而对于已经是utf-8未带bom，就认定不是乱码的。对于UTF-8 without BOM与GBK还无法判断，该代码会把UTF-8判断未GBK，导致出现问题。

**Comment by briarbear** [comment]
😂😂🤣，主要用来gbk转utf-8 其他没做太多严重发自我的华为手机-------- 原始邮件 --------主题：[briarbear/gbk_to_utf8] 识别不了不带bom的UTF-8 (#1)发件人：yansheng836 收件人：briarbear/gbk_to_utf8 抄送：Subscribed UTF-8带BOM和UTF-8不带BOM是不一样的，你这个程序检测不出来不带bom的UTF-8。

亲测：

如果你确认你需要转的文件全是gbk，该程序可以实现批量转UTF-8（不带bom的）；但是如果你继续用该程序扫描该文件夹，那么恭喜你😇全乱了（如需尝试，请预先备份重要文件）。
